################
GET http://localhost:8080

################
GET http://localhost:8080/athlete


################
GET http://localhost:8080/athlete/41803353/zones

################
GET http://localhost:8080/athlete/41803353/stats

################
GET http://localhost:8080/athlete/activities

################
GET http://localhost:8080/athlete/activities/13304198003
################
POST http://localhost:8080/embeddings
Content-Type: application/json

{
    "value": "Hello"
}

################

GET http://localhost:8080/athlete/41803353/activities?page=1&perPage=10
################
GET http://localhost:8080/vector-search?query="When did the Monarch Company exist?"

################
GET http://localhost:8080/athlete/41803353/selected-activities?activityIds=13436599434,13427630075